# Generated by Django 5.2 on 2025-04-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("login_id", models.CharField(max_length=50, unique=True)),
                (
                    "auth_id",
                    models.CharField(
                        choices=[("admin", "운영자"), ("user", "일반회원")],
                        default="user",
                        max_length=10,
                    ),
                ),
                ("pwd", models.CharField(max_length=128)),
                ("nickname", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
