# Generated by Django 5.2 on 2025-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default.jpg",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
