# Generated by Django 5.2.1 on 2025-05-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_blockeduser_reporteduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
