# Generated by Django 5.2.1 on 2025-05-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_blockeduser_reporteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='greeting_message',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
