# Generated by Django 5.2.1 on 2025-05-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('change_rate', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'date'], name='predict_sto_code_39144a_idx')],
                'unique_together': {('code', 'date')},
            },
        ),
    ]
