# Generated by Django 5.2 on 2025-05-09 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DartDisclosure",
            fields=[
                (
                    "corp_code",
                    models.CharField(
                        help_text="공시대상회사의 고유번호(8자리)", max_length=8
                    ),
                ),
                (
                    "corp_name",
                    models.CharField(help_text="공시대상회사명", max_length=255),
                ),
                (
                    "stock_code",
                    models.CharField(
                        blank=True,
                        help_text="상장회사의 종목코드(6자리)",
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "corp_cls",
                    models.CharField(
                        help_text="법인구분 : Y(유가), K(코스닥), N(코넥스), E(기타)",
                        max_length=1,
                    ),
                ),
                ("report_nm", models.CharField(help_text="보고서명", max_length=255)),
                (
                    "rcept_no",
                    models.CharField(
                        help_text="접수번호(14자리)",
                        max_length=14,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("flr_nm", models.CharField(help_text="공시 제출인명", max_length=255)),
                ("rcept_dt", models.DateField(help_text="접수일자(YYYYMMDD)")),
                (
                    "rm",
                    models.CharField(
                        blank=True, help_text="비고", max_length=10, null=True
                    ),
                ),
                (
                    "doc_url",
                    models.URLField(
                        blank=True,
                        help_text="공시뷰어 URL (doc.dart.fss.or.kr)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "report_link",
                    models.URLField(
                        blank=True,
                        help_text="원문 DART 링크 (dart.fss.or.kr)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "document_content",
                    models.TextField(
                        blank=True, help_text="공시 상세 본문 내용", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "DART 공시 정보",
                "verbose_name_plural": "DART 공시 정보 목록",
                "ordering": ["-rcept_dt", "-rcept_no"],
            },
        ),
        migrations.CreateModel(
            name="FreeBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("up_dt", models.DateTimeField(auto_now=True)),
                ("likes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("잡담", "잡담"),
                            ("실시간뉴스", "실시간뉴스"),
                            ("수동공시", "수동공시"),
                            ("API공시", "API공시"),
                        ],
                        db_index=True,
                        default="잡담",
                        max_length=20,
                    ),
                ),
                (
                    "dart_rcept_no",
                    models.CharField(
                        blank=True,
                        help_text="DART API 공시의 경우 원본 접수번호",
                        max_length=14,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreeBoardComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("up_dt", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "free_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="community.freeboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_board_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FreeBoardLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                (
                    "free_board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="community.freeboard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="free_board_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("free_board", "user")},
            },
        ),
    ]
