# Generated by Django 5.2.1 on 2025-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeboard",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="community_images/"
            ),
        ),
    ]
