# Generated by Django 5.2 on 2025-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_freeboard_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="뉴스 기사 제목", max_length=255)),
                (
                    "original_link",
                    models.URLField(
                        help_text="뉴스 원문 링크 (중복 방지용)",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "naver_link",
                    models.URLField(
                        blank=True,
                        help_text="네이버 뉴스 링크 (API 제공 링크)",
                        max_length=500,
                        null=True,
                    ),
                ),
                ("description", models.TextField(help_text="뉴스 요약 내용")),
                ("pub_date", models.DateTimeField(help_text="뉴스 발행 일시")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="DB 저장 시각"),
                ),
            ],
            options={
                "verbose_name": "네이버 뉴스 기사",
                "verbose_name_plural": "네이버 뉴스 기사 목록",
                "ordering": ["-pub_date"],
            },
        ),
    ]
