# Generated by Django 5.2.1 on 2025-05-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_freeboard_image"),
    ]

    operations = []
