# Generated by Django 5.2.1 on 2025-05-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeboard",
            name="worried_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
