# Generated by Django 5.2 on 2025-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_freeboard_comments_count_freeboard_likes_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disclosure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disclosure_type", models.CharField(max_length=50)),
                ("date", models.DateField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
    ]
