# Generated by Django 5.2.1 on 2025-05-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_freeboard_worried_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="freeboardlike",
            name="action",
            field=models.CharField(
                choices=[("like", "좋아요"), ("worry", "걱정돼요")],
                default="like",
                max_length=10,
            ),
        ),
    ]
