# Generated by Django 5.2.1 on 2025-05-16 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0003_auto_20250514_2005"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="admin_board_images/"
                    ),
                ),
                ("reg_dt", models.DateTimeField(auto_now_add=True)),
                ("up_dt", models.DateTimeField(auto_now=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_boards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "관리자 게시글",
                "verbose_name_plural": "관리자 게시글 목록",
                "ordering": ["-reg_dt"],
            },
        ),
    ]
