# Generated by Django 5.2.1 on 2025-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0004_freeboardlike_action"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="freeboardlike",
            name="action",
        ),
        migrations.AddField(
            model_name="freeboardlike",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="freeboardlike",
            name="is_worried",
            field=models.BooleanField(default=False),
        ),
    ]
