# Generated by Django 5.2.1 on 2025-05-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=10, verbose_name='시장 구분')),
                ('date', models.DateField(verbose_name='날짜')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('previous_day_close_price', models.FloatField(blank=True, null=True, verbose_name='전일 종가')),
                ('change_value', models.FloatField(blank=True, null=True, verbose_name='대비')),
                ('change_percent', models.FloatField(blank=True, null=True, verbose_name='등락률 (%)')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
                ('trade_value', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
            ],
            options={
                'verbose_name': '일별 시장 지수',
                'verbose_name_plural': '일별 시장 지수 목록',
                'ordering': ['-date', 'market_name'],
                'unique_together': {('market_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='종목 코드')),
                ('stock_name', models.CharField(max_length=100, verbose_name='종목명')),
                ('market_name', models.CharField(help_text='예: KOSPI, KOSDAQ', max_length=10, verbose_name='시장 구분')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='시가')),
                ('high_price', models.FloatField(blank=True, null=True, verbose_name='고가')),
                ('low_price', models.FloatField(blank=True, null=True, verbose_name='저가')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('previous_day_close_price', models.FloatField(blank=True, null=True, verbose_name='전일 종가')),
                ('change_value', models.FloatField(blank=True, null=True, verbose_name='대비')),
                ('change_percent', models.FloatField(blank=True, null=True, verbose_name='등락률 (%)')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
                ('trade_value', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
            ],
            options={
                'verbose_name': '개별 종목 가격',
                'verbose_name_plural': '개별 종목 가격 목록',
                'ordering': ['-date', 'stock_name'],
                'indexes': [models.Index(fields=['date', 'market_name', '-change_percent'], name='predict_inf_date_9ca942_idx'), models.Index(fields=['date', 'stock_name'], name='predict_inf_date_b20221_idx'), models.Index(fields=['date', 'stock_code'], name='predict_inf_date_e52de7_idx')],
                'unique_together': {('stock_code', 'date')},
            },
        ),
    ]
