# Generated by Django 5.2.1 on 2025-05-24 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥')], max_length=10, verbose_name='시장 구분')),
                ('date', models.DateField(verbose_name='날짜')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('previous_day_close_price', models.FloatField(blank=True, null=True, verbose_name='전일 종가')),
                ('change_value', models.FloatField(blank=True, null=True, verbose_name='대비')),
                ('change_percent', models.FloatField(blank=True, null=True, verbose_name='등락률 (%)')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
                ('trade_value', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
            ],
            options={
                'verbose_name': '일별 시장 지수',
                'verbose_name_plural': '일별 시장 지수 목록',
                'ordering': ['-date', 'market_name'],
                'unique_together': {('market_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PredictedStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20, verbose_name='종목 코드')),
                ('stock_name', models.CharField(blank=True, max_length=100, verbose_name='종목명')),
                ('market_name', models.CharField(blank=True, max_length=10, verbose_name='시장 구분')),
                ('prediction_base_date', models.DateField(db_index=True, help_text='이 날짜의 종가까지를 기반으로 예측이 수행됨', verbose_name='예측 기준일')),
                ('predicted_date', models.DateField(help_text='실제 주가가 예측된 미래의 날짜', verbose_name='예측 대상일')),
                ('predicted_price', models.FloatField(verbose_name='예측 종가')),
                ('analysis_type', models.CharField(choices=[('technical', '기술적 분석'), ('comprehensive', '종합 분석')], default='technical', max_length=20, verbose_name='분석 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '종목별 예측 가격',
                'verbose_name_plural': '종목별 예측 가격 목록',
                'ordering': ['-prediction_base_date', 'stock_code', 'predicted_date'],
                'indexes': [models.Index(fields=['stock_code', 'prediction_base_date', 'analysis_type', 'predicted_date'], name='pred_price_lookup_idx'), models.Index(fields=['prediction_base_date'], name='predict_inf_predict_756ea1_idx')],
                'unique_together': {('stock_code', 'prediction_base_date', 'predicted_date', 'analysis_type')},
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='종목 코드')),
                ('stock_name', models.CharField(max_length=100, verbose_name='종목명')),
                ('market_name', models.CharField(help_text='예: KOSPI, KOSDAQ', max_length=10, verbose_name='시장 구분')),
                ('date', models.DateField(verbose_name='날짜')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='시가')),
                ('high_price', models.FloatField(blank=True, null=True, verbose_name='고가')),
                ('low_price', models.FloatField(blank=True, null=True, verbose_name='저가')),
                ('close_price', models.FloatField(verbose_name='종가')),
                ('previous_day_close_price', models.FloatField(blank=True, null=True, verbose_name='전일 종가')),
                ('change_value', models.FloatField(blank=True, null=True, verbose_name='대비')),
                ('change_percent', models.FloatField(blank=True, null=True, verbose_name='등락률 (%)')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='거래량')),
                ('trade_value', models.BigIntegerField(blank=True, null=True, verbose_name='거래대금')),
                ('indi_volume', models.BigIntegerField(blank=True, help_text='개인 투자자 순매수량 (주)', null=True, verbose_name='개인 순매수 거래량')),
                ('foreign_volume', models.BigIntegerField(blank=True, help_text='외국인 투자자 순매수량 (주)', null=True, verbose_name='외국인 순매수 거래량')),
                ('organ_volume', models.BigIntegerField(blank=True, help_text='기관 투자자 순매수량 (주)', null=True, verbose_name='기관 순매수 거래량')),
                ('market_cap', models.BigIntegerField(blank=True, help_text='해당일의 시가총액 또는 최근 스냅샷 값', null=True, verbose_name='시가총액 (원)')),
                ('per', models.FloatField(blank=True, help_text='Price Earning Ratio', null=True, verbose_name='PER')),
                ('pbr', models.FloatField(blank=True, help_text='Price Book-value Ratio', null=True, verbose_name='PBR')),
            ],
            options={
                'verbose_name': '개별 종목 상세 정보',
                'verbose_name_plural': '개별 종목 상세 정보 목록',
                'ordering': ['-date', 'stock_name'],
                'indexes': [models.Index(fields=['date', 'market_name', '-change_percent'], name='predict_inf_date_9ca942_idx'), models.Index(fields=['date', 'stock_name'], name='predict_inf_date_b20221_idx'), models.Index(fields=['date', 'stock_code'], name='predict_inf_date_e52de7_idx'), models.Index(fields=['stock_code', 'date'], name='stock_date_idx')],
                'unique_together': {('stock_code', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='종목 코드')),
                ('stock_name', models.CharField(blank=True, max_length=100, verbose_name='종목명')),
                ('market_name', models.CharField(blank=True, max_length=20, verbose_name='시장 구분')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 시각')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stocks', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '관심 종목',
                'verbose_name_plural': '관심 종목 목록',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'stock_code')},
            },
        ),
    ]
