# Generated by Django 5.2 on 2025-05-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20, verbose_name='종목 코드')),
                ('stock_name', models.CharField(blank=True, max_length=100, verbose_name='종목명')),
                ('market_name', models.CharField(blank=True, max_length=10, verbose_name='시장 구분')),
                ('prediction_base_date', models.DateField(db_index=True, help_text='이 날짜의 종가까지를 기반으로 예측이 수행됨', verbose_name='예측 기준일')),
                ('predicted_date', models.DateField(help_text='실제 주가가 예측된 미래의 날짜', verbose_name='예측 대상일')),
                ('predicted_price', models.FloatField(verbose_name='예측 종가')),
                ('analysis_type', models.CharField(choices=[('technical', '기술적 분석'), ('comprehensive', '종합 분석')], default='technical', max_length=20, verbose_name='분석 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
            ],
            options={
                'verbose_name': '종목별 예측 가격',
                'verbose_name_plural': '종목별 예측 가격 목록',
                'ordering': ['-prediction_base_date', 'stock_code', 'predicted_date'],
                'indexes': [models.Index(fields=['stock_code', 'prediction_base_date', 'analysis_type', 'predicted_date'], name='pred_price_lookup_idx'), models.Index(fields=['prediction_base_date'], name='predict_inf_predict_756ea1_idx')],
                'unique_together': {('stock_code', 'prediction_base_date', 'predicted_date', 'analysis_type')},
            },
        ),
    ]
