# Generated by Django 5.2 on 2025-05-22 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_info', '0002_predictedstockprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, verbose_name='종목 코드')),
                ('stock_name', models.CharField(blank=True, max_length=100, verbose_name='종목명')),
                ('market_name', models.CharField(blank=True, max_length=20, verbose_name='시장 구분')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='추가된 시각')),
            ],
            options={
                'verbose_name': '관심 종목',
                'verbose_name_plural': '관심 종목 목록',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-date', 'stock_name'], 'verbose_name': '개별 종목 상세 정보', 'verbose_name_plural': '개별 종목 상세 정보 목록'},
        ),
        migrations.AddField(
            model_name='stockprice',
            name='foreign_volume',
            field=models.BigIntegerField(blank=True, help_text='외국인 투자자 순매수량 (주)', null=True, verbose_name='외국인 순매수 거래량'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='indi_volume',
            field=models.BigIntegerField(blank=True, help_text='개인 투자자 순매수량 (주)', null=True, verbose_name='개인 순매수 거래량'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='market_cap',
            field=models.BigIntegerField(blank=True, help_text='해당일의 시가총액 또는 최근 스냅샷 값', null=True, verbose_name='시가총액 (원)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='organ_volume',
            field=models.BigIntegerField(blank=True, help_text='기관 투자자 순매수량 (주)', null=True, verbose_name='기관 순매수 거래량'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='pbr',
            field=models.FloatField(blank=True, help_text='Price Book-value Ratio', null=True, verbose_name='PBR'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='per',
            field=models.FloatField(blank=True, help_text='Price Earning Ratio', null=True, verbose_name='PER'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock_code', 'date'], name='stock_date_idx'),
        ),
        migrations.AddField(
            model_name='favoritestock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_stocks', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritestock',
            unique_together={('user', 'stock_code')},
        ),
    ]
