# Generated by Django 5.2.1 on 2025-05-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predict_info", "0003_favoritestock_alter_stockprice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockprice",
            name="bps",
            field=models.FloatField(
                blank=True,
                help_text="Book-value Per Share",
                null=True,
                verbose_name="BPS",
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="dps",
            field=models.FloatField(
                blank=True,
                help_text="Dividend Per Share",
                null=True,
                verbose_name="DPS",
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="eps",
            field=models.FloatField(
                blank=True,
                help_text="Earnings Per Share",
                null=True,
                verbose_name="EPS",
            ),
        ),
        migrations.AddField(
            model_name="stockprice",
            name="roe",
            field=models.FloatField(
                blank=True, help_text="Return On Equity", null=True, verbose_name="ROE"
            ),
        ),
    ]
