# Generated by Django 5.2 on 2025-05-27 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict_info', '0004_stockprice_bps_stockprice_dps_stockprice_eps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritestock',
            options={'ordering': ['user', '-added_at'], 'verbose_name': '관심 종목', 'verbose_name_plural': '관심 종목 목록'},
        ),
        migrations.AlterModelOptions(
            name='predictedstockprice',
            options={'ordering': ['-prediction_base_date', 'stock_code', 'predicted_date'], 'verbose_name': '주가 예측 결과', 'verbose_name_plural': '주가 예측 결과 목록'},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-date', 'stock_code'], 'verbose_name': '일별 주가 및 피처', 'verbose_name_plural': '일별 주가 및 피처 목록'},
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='predict_inf_date_9ca942_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='predict_inf_date_b20221_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockprice',
            name='predict_inf_date_e52de7_idx',
        ),
        migrations.RemoveField(
            model_name='predictedstockprice',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='change_percent',
        ),
        migrations.RemoveField(
            model_name='stockprice',
            name='trade_value',
        ),
        migrations.AddField(
            model_name='predictedstockprice',
            name='model_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='사용 모델 버전'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='ADX14',
            field=models.FloatField(blank=True, null=True, verbose_name='ADX (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='ATR14',
            field=models.FloatField(blank=True, null=True, verbose_name='ATR (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='BB_Lower',
            field=models.FloatField(blank=True, null=True, verbose_name='볼린저밴드 하단'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='BB_Middle',
            field=models.FloatField(blank=True, null=True, verbose_name='볼린저밴드 중간'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='BB_PercentB',
            field=models.FloatField(blank=True, null=True, verbose_name='볼린저밴드 %B'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='BB_Upper',
            field=models.FloatField(blank=True, null=True, verbose_name='볼린저밴드 상단'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='BB_Width',
            field=models.FloatField(blank=True, null=True, verbose_name='볼린저밴드 폭'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='CCI14',
            field=models.FloatField(blank=True, null=True, verbose_name='CCI (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='DMN14',
            field=models.FloatField(blank=True, null=True, verbose_name='DI- (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='DMP14',
            field=models.FloatField(blank=True, null=True, verbose_name='DI+ (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='EMA10',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA (10일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='EMA120',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA (120일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='EMA20',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA (20일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='EMA5',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA (5일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='EMA60',
            field=models.FloatField(blank=True, null=True, verbose_name='EMA (60일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='HL_spread',
            field=models.FloatField(blank=True, null=True, verbose_name='고가-저가 Spread'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MA10',
            field=models.FloatField(blank=True, null=True, verbose_name='MA (10일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MA120',
            field=models.FloatField(blank=True, null=True, verbose_name='MA (120일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MA20',
            field=models.FloatField(blank=True, null=True, verbose_name='MA (20일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MA5',
            field=models.FloatField(blank=True, null=True, verbose_name='MA (5일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MA60',
            field=models.FloatField(blank=True, null=True, verbose_name='MA (60일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MACD',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MACD_Hist',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD Histogram'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MACD_Signal',
            field=models.FloatField(blank=True, null=True, verbose_name='MACD Signal'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='MFI14',
            field=models.FloatField(blank=True, null=True, verbose_name='MFI (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='Market_Index_Change',
            field=models.FloatField(blank=True, null=True, verbose_name='해당일 시장 지수 등락률'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='Market_Index_Close',
            field=models.FloatField(blank=True, null=True, verbose_name='해당일 시장 지수 종가'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='Momentum',
            field=models.FloatField(blank=True, null=True, verbose_name='Momentum (10일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='OBV',
            field=models.FloatField(blank=True, null=True, verbose_name='OBV'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='OC_spread',
            field=models.FloatField(blank=True, null=True, verbose_name='시가-종가 Spread'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='PSY',
            field=models.FloatField(blank=True, null=True, verbose_name='PSY (12일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='ROC',
            field=models.FloatField(blank=True, null=True, verbose_name='ROC (10일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='RSI14',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='RSI28',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI (28일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='RSI6',
            field=models.FloatField(blank=True, null=True, verbose_name='RSI (6일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='STOCH_D',
            field=models.FloatField(blank=True, null=True, verbose_name='Stochastic %D (Slow)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='STOCH_K',
            field=models.FloatField(blank=True, null=True, verbose_name='Stochastic %K (Slow)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='STOCH_SLOW_D',
            field=models.FloatField(blank=True, null=True, verbose_name='Stochastic %D (Fast)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='STOCH_SLOW_K',
            field=models.FloatField(blank=True, null=True, verbose_name='Stochastic %K (Fast)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='TRIX',
            field=models.FloatField(blank=True, null=True, verbose_name='TRIX (14일, Signal 9일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='USD_KRW_Change',
            field=models.FloatField(blank=True, null=True, verbose_name='해당일 원/달러 환율 등락률'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='USD_KRW_Close',
            field=models.FloatField(blank=True, null=True, verbose_name='해당일 원/달러 환율 종가'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='VR',
            field=models.FloatField(blank=True, null=True, verbose_name='VR (20일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='WilliamsR14',
            field=models.FloatField(blank=True, null=True, verbose_name='Williams %R (14일)'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='change',
            field=models.FloatField(blank=True, null=True, verbose_name='등락률'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockprice',
            name='log_close_price',
            field=models.FloatField(blank=True, null=True, verbose_name='로그 변환 종가'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='log_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='로그 변환 거래량'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='market_cap_is_nan',
            field=models.BooleanField(blank=True, null=True, verbose_name='시가총액 NaN 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='pbr_is_high',
            field=models.BooleanField(blank=True, null=True, verbose_name='PBR 고평가 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='pbr_is_low',
            field=models.BooleanField(blank=True, null=True, verbose_name='PBR 저평가 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='pbr_is_nan',
            field=models.BooleanField(blank=True, null=True, verbose_name='PBR NaN 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='pbr_is_zero',
            field=models.BooleanField(blank=True, null=True, verbose_name='PBR 0 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='per_is_high',
            field=models.BooleanField(blank=True, null=True, verbose_name='PER 고평가 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='per_is_low',
            field=models.BooleanField(blank=True, null=True, verbose_name='PER 저평가 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='per_is_nan',
            field=models.BooleanField(blank=True, null=True, verbose_name='PER NaN 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='per_is_zero',
            field=models.BooleanField(blank=True, null=True, verbose_name='PER 0 여부'),
        ),
        migrations.AddField(
            model_name='stockprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='수정 시간'),
        ),
        migrations.AlterField(
            model_name='favoritestock',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='추가된 날짜'),
        ),
        migrations.AlterField(
            model_name='predictedstockprice',
            name='analysis_type',
            field=models.CharField(choices=[('technical', '기술적 분석 기반 LSTM'), ('comprehensive', '종합 분석 기반 LSTM'), ('ipynb_kospi_lstm', 'ipynb KOSPI LSTM'), ('ipynb_kosdaq_lstm', 'ipynb KOSDAQ LSTM')], default='technical', max_length=100, verbose_name='분석 유형'),
        ),
        migrations.AlterField(
            model_name='predictedstockprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성 시간'),
        ),
        migrations.AlterField(
            model_name='predictedstockprice',
            name='market_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='시장 구분'),
        ),
        migrations.AlterField(
            model_name='predictedstockprice',
            name='predicted_date',
            field=models.DateField(verbose_name='예측 대상일'),
        ),
        migrations.AlterField(
            model_name='predictedstockprice',
            name='prediction_base_date',
            field=models.DateField(verbose_name='예측 기준일'),
        ),
        migrations.AlterField(
            model_name='predictedstockprice',
            name='stock_code',
            field=models.CharField(max_length=20, verbose_name='종목 코드'),
        ),
        migrations.AlterField(
            model_name='predictedstockprice',
            name='stock_name',
            field=models.CharField(max_length=100, verbose_name='종목명'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='bps',
            field=models.FloatField(blank=True, null=True, verbose_name='BPS'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='change_value',
            field=models.FloatField(blank=True, null=True, verbose_name='대비 가격'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='close_price',
            field=models.FloatField(blank=True, null=True, verbose_name='종가'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='dps',
            field=models.FloatField(blank=True, null=True, verbose_name='DPS'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='eps',
            field=models.FloatField(blank=True, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='foreign_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='외국인 순매수(금액 또는 수량)'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='indi_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='개인 순매수(금액 또는 수량)'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='시가총액'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='market_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='시장 구분'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='organ_volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='기관 순매수(금액 또는 수량)'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='pbr',
            field=models.FloatField(blank=True, null=True, verbose_name='PBR'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='per',
            field=models.FloatField(blank=True, null=True, verbose_name='PER'),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='roe',
            field=models.FloatField(blank=True, null=True, verbose_name='ROE'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['stock_name'], name='predict_inf_stock_n_da1d0b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockprice',
            index=models.Index(fields=['market_name'], name='predict_inf_market__a2a94f_idx'),
        ),
    ]
